const jwt = require('jsonwebtoken')
var decoded = jwt.verify('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXNwb25zZSI6eyJzdGF0dXMiOiIyMDAiLCJpc0F1dGhlbnRpY2F0ZWQiOiJ0cnVlIiwiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbImVkaXRvciIsInVzZXIiLCJtb2QiXSwieC1oYXN1cmEtZGVmYXVsdC1yb2xlIjoidXNlciIsIngtaGFzdXJhLXVzZXItaWQiOiIxMjM0NTY3ODkwIiwieC1oYXN1cmEtb3JnLWlkIjoiMTIzIiwieC1oYXN1cmEtY3VzdG9tIjoiY3VzdG9tLXZhbHVlIn19LCJpYXQiOjE1Njg0OTEwMTZ9.B3QbepBYo0I8pAOiR9mqppyDfCpV7qgJqQkzMMahuFE', 'ilovefuckingbitches')
console.log(decoded)
